### ISSUE TITLE
Where is the model?

### ISSUE THREAD

**Issue by gevezex** [stefan-it/turkish-bert#1]
So where can we download the TR trained model?

**Comment by stefan-it** [comment]
Hi @gevezex ,

training of the models (both cased and uncased) is currently in progress.

The cased model is now at 1.4M steps, uncased model at 0.5M steps. 

I updated the README with links to the TensorBoards.

After evaluation (I plan to evaluate the models on PoS and NER datasets from [here](https://github.com/UKPLab/linspector/tree/master/extrinsic)), I'll upload the models to the Huggin Face model hub.

I think training and evaluation of the cased model will be finished until Friday, so stay tuned!

**Comment by gevezex** [comment]
Great! Bert Multilingual performed very bad on that dataset, so I am very curious about your trained model.

**Comment by TharinduDR** [comment]
Hi @gevezex, 

Thank you for the repo. Did you finish the training?

**Comment by stefan-it** [comment]
Hey guys,

the model is now uploaded to the Hugging Face model hub:

https://huggingface.co/dbmdz/bert-base-turkish-cased

You can directly use it in the Transformers library :)

Uncased model is coming next week (training has finished, only evaluation is missing).

**Comment by anilozdemir96** [comment]
Hello Stefan,

First of all, thank you for such a good repository.  Can we use the model for a sentiment classification task ?

**Comment by serdar-eric** [comment]
Hi @stefan-it . 
Any updates about the uncased model?

**Comment by stefan-it** [comment]
Hi @serdar-eric ,

uncased model will be released this week. Additionally, I also trained cased and uncased models with a larger vocab size (128k instead of 32k), I'm currently doing the evaluation, but I think it will be ready until Sunday :)

**Comment by serdar-eric** [comment]
> Hi @serdar-eric ,
> 
> uncased model will be released this week. Additionally, I also trained cased and uncased models with a larger vocab size (128k instead of 32k), I'm currently doing the evaluation, but I think it will be ready until Sunday :)

It's great to hear that @stefan-it . Thank you very much

**Comment by stefan-it** [comment]
Hi @serdar-eric ,

the uncased model is now available from model hub: https://huggingface.co/dbmdz/bert-base-turkish-uncased.

Additionally, you can now find models with a larger vocab size (128k) on the model hub:

* https://huggingface.co/dbmdz/bert-base-turkish-128k-cased
* https://huggingface.co/dbmdz/bert-base-turkish-128k-uncased

**Comment by serdar-eric** [comment]
Thank you very much @stefan-it . Already started to download and work on it :)

**Comment by balki7** [comment]
Stefan, 
I need 128K TF model for comparing with 32K.
Could u share?
Thanx a lot! :)

**Comment by balki7** [comment]
@stefan-it Stefan, reminder. 
I've short time to submit the thesis.
BTW, your Github repo link is on my references... :)
Thanx a lot.

**Comment by stefan-it** [comment]
@balki7 no problem, I'm currently preparing the archives :)

**Comment by stefan-it** [comment]
Download links are now available:

```bash
# sha256: 85977347ef031c5cf5f41bd79342e1548b119a1c5b1e7c5dcc1cae4855c4d2b1
wget https://schweter.eu/cloud/bert-base-turkish-128k-cased/bert-base-turkish-128k-cased-tf.tar.gz

# sha256: b73916ee54a25b1a75df87f55dea4adbc8b61b6f82ef0983e556b1007e3be3df
wget https://schweter.eu/cloud/bert-base-turkish-128k-uncased/bert-base-turkish-128k-uncased-tf.tar.gz
```

Please let me know if the checkpoints are working + good luck with your thesis :)

**Comment by balki7** [comment]
Çok teşekkür ederim Stefan... :)
