### ISSUE TITLE
Bibtext

### ISSUE THREAD

**Issue by anilozdemir96** [stefan-it/turkish-bert#11]
Hello Stefan,

How can we cite turkish-bert for our academic papers ?

Thanks,

**Comment by stefan-it** [comment]
Hi @anilozdemir96 ,

sorry for the long response time!

I've just connected this repo with Zenodo and prepared the first release. You can now use the following BibTeX entry:

```bibtex
@software{stefan_schweter_2020_3770924,
  author       = {Stefan Schweter},
  title        = {BERTurk - BERT models for Turkish},
  month        = apr,
  year         = 2020,
  publisher    = {Zenodo},
  version      = {1.0.0},
  doi          = {10.5281/zenodo.3770924},
  url          = {https://doi.org/10.5281/zenodo.3770924}
}
```

when you want to cite the model(s) :)

**Comment by anilozdemir96** [comment]
Thank you so much Stefan !.
