### ISSUE TITLE
Summarization and Classificaiton fine-tune

### ISSUE THREAD

**Issue by savasy** [stefan-it/turkish-bert#12]
Hi @stefan-it , is there any training code in transformer repo or else where such as run_glue.py or run_ner.py to fine-tune Turkish-bert model  for the summarization and classificaiton problem ?

**Comment by stefan-it** [comment]
Hi @savasy ,

for text summarization you would need a sequence-to-sequence model architecture, e.g. like the recently introduced BART model: https://arxiv.org/abs/1910.13461

For classification you could modify the `run_glue.py` script. However, there are simpler ways, like using [FARM](https://github.com/deepset-ai/FARM) or [simpletransformers](https://github.com/ThilinaRajapakse/simpletransformers) :)

**Comment by savasy** [comment]
Thank you @stefan-it for quick reply.
