### ISSUE TITLE
Electra Model

### ISSUE THREAD

**Issue by balki7** [stefan-it/turkish-bert#14]
Stefan, where can I download the ELECTRA model?
Again I need TF checkpoints, I'll fine-tune for MRQA.
Thanx a lot!

**Comment by stefan-it** [comment]
Hi  @balki7 ,

the ELECTRA models can be downloaded from the Hugging Face model hub:

* [ELECTRA small](https://huggingface.co/dbmdz/electra-small-turkish-cased-discriminator)
* [ELECTRA base](https://huggingface.co/dbmdz/electra-base-turkish-cased-discriminator)

TF checkpoints can be downloaded from here:

```bash
wget https://schweter.eu/storage/electra-small-turkish-cased/electra-small-turkish-cased-tf.tar.gz
wget https://schweter.eu/storage/electra-base-turkish-cased/electra-base-turkish-cased-tf.tar.gz
```

Vocab is not included in the archives, but it's the same as for BERTurk, so you can download it from [here](https://s3.amazonaws.com/models.huggingface.co/bert/dbmdz/electra-small-turkish-cased-discriminator/vocab.txt).

I'm not sure what implementation you're using together with the TF checkpoints, so I can't recommend a `config.json` (but I think it should be the discriminator configuration, unless you want to play around with the generator model for masking stuff).

**Comment by balki7** [comment]
Thanx Stefan.
