### ISSUE TITLE
Any plan for Turkish T5?

### ISSUE THREAD

**Issue by monatis** [stefan-it/turkish-bert#17]
Hi @stefan-it, thanks a lot again for the great job you're doing here. Now that I'm planning to train a Turkish T5 from scratch, I just want to ask if you have any such plan to not duplicate the resources to be spent.

**Comment by stefan-it** [comment]
Hi @monatis , I haven't any plans for training a T5 model 😅

But I can tell you, that I've trained a Funnel Transformer and I'm waiting for the integration into Transformers for checkpoint evaluation 🤗

**Comment by monatis** [comment]
Thanks for the quick response @stefan-it. Funnel Transformer is just amazing and looking forward to it 🤗  I'll also look into T5 at the same time 🏃‍♂️
