### ISSUE TITLE
Tensorflow Checkpoints

### ISSUE THREAD

**Issue by balki7** [stefan-it/turkish-bert#2]
Hi,

Is it possible to share TF checkpoints?
Thanx a lot.

**Comment by julien-c** [comment]
FYI, in case you're using huggingface transformers, you *should* be able to load the PyTorch weights into a TF2 model, using the `from_pt=True` flag.

(of course, we could also convert the weights pretty easily and upload to S3, but in the meantime, you have this option)

**Comment by cansozbir** [comment]
@julien-c  I tried to run this

TFBertModel.from_pretrained("dbmdz/bert-base-turkish-cased", from_pt=True)
and got the error below.

OSError: Loading a TF model from a PyTorch checkpoint is not supported when using a model identifier name.

I'm trying this in google-colab with tensorflow 2.1.0 and gpu acclerator. Am I missing something?

**Comment by stefan-it** [comment]
@balki7 Sure, here are the original TF checkpoints (best checkpoint, incl. config and vocab):

```bash
wget https://schweter.eu/cloud/bert-base-turkish-cased/bert-base-turkish-cased-tf.tar.gz

# sha256 bert-base-turkish-cased-tf.tar.gz
# 8113d0aeb32a2e7bcd00027195a13622387ca9e2132d7f9a1b27389a0db26b96
```

**Comment by balki7** [comment]
> @balki7 Sure, here are the original TF checkpoints (best checkpoint, incl. config and vocab):
> 
> ```shell
> wget https://schweter.eu/cloud/bert-base-turkish-cased/bert-base-turkish-cased-tf.tar.gz
> 
> # sha256 bert-base-turkish-cased-tf.tar.gz
> # 8113d0aeb32a2e7bcd00027195a13622387ca9e2132d7f9a1b27389a0db26b96
> ```

Thank u so much Stefan.
