### ISSUE TITLE
bert uncased tf checkpoints

### ISSUE THREAD

**Issue by hazalturkmen** [stefan-it/turkish-bert#29]
Hi! @stefan-it 
i need to bert-base-32k-uncased tf chekpoints for further pre-training on Cloud TPU. I found cased version from this link 

> wget https://schweter.eu/cloud/bert-base-turkish-cased/bert-base-turkish-cased-tf.tar.gz

is it possible to get 32k uncased version of Turkish Bert model?

Thanks for all sharing,

**Comment by stefan-it** [comment]
Hi @hazalturkmen ,

in this archive you can find the last 5 checkpoints from the uncased model (I think I've chosen the 2M checkpoint for the final model):

```
wget wget https://schweter.eu/cloud/bert-base-turkish-uncased/bert-base-turkish-uncased.tar.gz
```

Hope this help :)

**Comment by hazalturkmen** [comment]
thanks for sharing model Stefan! 
this is what i was looking for :) 

how long did it take to train model from scratch? do you remember? its okay if you don't :)

**Comment by stefan-it** [comment]
Hey @hazalturkmen ,

sure, here you can the [TensorBoard](https://tensorboard.dev/experiment/5LlD11cWRwexyqKSEPPXGA/#scalars&runSelectionState=eyIuIjp0cnVlfQ%3D%3D) for the complete training:

8.2, 21:40 to 15.2, 08:25. So the training took ~6 days and 13,5 hours for 2M steps on a v3-8 TPU :hugs:

**Comment by hazalturkmen** [comment]
Hi @stefan-it ,

Finally, can I learn the tensorboard configuration for google cloud tpu? i have this error and i am using firefox browser

> Couldn't connect to a server on port 8080

Thank you so much :)

**Comment by hazalturkmen** [comment]
Hi @stefan-it ,
I want to dowload Turkish BERT uncased tf checkpoints from previous mention codes:
`wget wget https://schweter.eu/cloud/bert-base-turkish-uncased/bert-base-turkish-uncased.tar.gz`

but I get an error in downloading. I would be very grateful if you help me :)

**Comment by julien-c** [comment]
@hazalturkmen maybe from here: https://huggingface.co/dbmdz/bert-base-turkish-uncased

**Comment by hazalturkmen** [comment]
Thanks! @stefan-it

**Comment by hazalturkmen** [comment]
Thanks! @stefan-it
