### ISSUE TITLE
Traning Duration

### ISSUE THREAD

**Issue by sahinbatmaz** [stefan-it/turkish-bert#4]
Hi, how long does it take to train a BERT base model in the configuration of Cloud TPU v3-8, 4.4B words, 32K vocabulary size and 512 sequence length ?

**Comment by stefan-it** [comment]
Hi @sahinbatmaz ,

for 2M steps (which are sufficient) it takes 7 days (this is consistent with other BERT models I've trained) :)

**Comment by sahinbatmaz** [comment]
Thanks for the answer and the repository :)
