### ISSUE TITLE
Multiclass Classification

### ISSUE THREAD

**Issue by ozcangundes** [stefan-it/turkish-bert#5]
Hi,
I could not find any argument to pass number of classes in [AutoModel](https://github.com/huggingface/transformers/blob/38f5fe9e0277df67a01db80a1c640ac072a2381e/src/transformers/modeling_auto.py#L240) codes to apply sentiment analysis with BERTurk. Do I miss something? Thanks in advance.
```python
from transformers import AutoModelForSequenceClassification, AdamW, AutoConfig,AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("dbmdz/bert-base-turkish-cased")
model = AutoModelForSequenceClassification.from_pretrained(
    "dbmdz/bert-base-turkish-cased")
```

**Comment by stefan-it** [comment]
Hi @ozcangundes ,

sorry for the late reply!

I think you should look into the glue example from the Transformers library (as they also do classification):

https://github.com/huggingface/transformers/blob/master/examples/run_glue.py#L215-L222

So for multi class I think you can use this code example:

https://github.com/huggingface/transformers/blob/master/examples/run_glue.py#L416

```python
 all_labels = torch.tensor([f.label for f in features], dtype=torch.long)
```

Please let us know, if that works!

**Comment by ozcangundes** [comment]
Hi @stefan-it,

Thank you for your response. I could not actually solve it in your way but by passing num_label argument to config_class, it worked. Here is my solution:

```python

config = AutoConfig.from_pretrained(
        "dbmdz/bert-base-turkish-cased",num_labels=4)
model = AutoModelForSequenceClassification.from_pretrained(
    "dbmdz/bert-base-turkish-cased",config=config)

model.cuda()
```

**Comment by hosjiu1702** [comment]
> Hi @stefan-it,
> 
> Thank you for your response. I could not actually solve it in your way but by passing num_label argument to config_class, it worked. Here is my solution:
> 
> ```python
> config = AutoConfig.from_pretrained(
>         "dbmdz/bert-base-turkish-cased",num_labels=4)
> model = AutoModelForSequenceClassification.from_pretrained(
>     "dbmdz/bert-base-turkish-cased",config=config)
> 
> model.cuda()
> ```

You do not need to use `AutoConfig` if what you care just a configuration attribute which here in your case was `num_labels`.

All you need is setting keyword argument `num_labels` inside constructor of `AutoModelForSequenceClassification` as following:

`model = AutoModelForSequenceClassification.from_pretrained("dbmdz/bert-base-turkish-cased", num_labels=4)`
