### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by balki7** [stefan-it/turkish-bert#8]
Stefan,

Is it possible to share the commands that you've used for generating the model?
I'll add some domain specific data to the model and for retraining I need you commands.

Thanx a lot.

**Comment by stefan-it** [comment]
Hi @balki7 ,

thanks for your interest 🤗

I did document the training commands in [this cheatsheet](https://github.com/stefan-it/turkish-bert/blob/master/CHEATSHEET.md).

But if you just want to fine-tune the language model, I think you can also use the Transformers library. More precisely, you could use the steps documented here:

https://github.com/huggingface/transformers/tree/master/examples#language-model-training

:)

**Comment by balki7** [comment]
Thanx Stefan again and again.
My MS Thesis is related to BERT in Turkish.
If it is OK for you, I'll point your project also. :)

**Comment by stefan-it** [comment]
Hi @balki7 ,

sure, that would be awesome :)

Just a few upcoming news: uncased BERT model is coming soon. And I've trained cased and uncased models with a larger vocab size (128k instead of 32k). Only evaluation is only missing.
